// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gympack

import (
	"github.com/google/wire"
	"gympack/pkg/domain/usecase/pack/create"
	"gympack/pkg/infrastructure/database/mongodb"
	"gympack/pkg/infrastructure/database/mongodb/repository/pack"
	"gympack/pkg/presentation"
	"gympack/pkg/presentation/middleware"
	"gympack/pkg/presentation/route"
	"gympack/pkg/shared"
)

// Injectors from wire.go:

func InitializeLoader() *presentation.Loader {
	configInterface := shared.NewConfig()
	dtoValidationMiddleware := middlewares.NewDtoValidationMiddleware()
	loggerInterface := shared.NewLogger(configInterface)
	mongoDbProviderInterface := provider.NewMongoDbProvider(configInterface)
	packRepositoryInterface := pack.NewPackRepository(mongoDbProviderInterface)
	createPackUseCaseInterface := create.NewCreatePackUseCase(loggerInterface, packRepositoryInterface)
	packRoute := route.NewPackRoute(dtoValidationMiddleware, createPackUseCaseInterface)
	loader := presentation.NewLoader(configInterface, packRoute, loggerInterface)
	return loader
}

// wire.go:

var superSet = wire.NewSet(presentation.NewLoader, shared.NewConfig, middlewares.NewDtoValidationMiddleware, create.NewCreatePackUseCase, route.NewPackRoute, shared.NewLogger, provider.NewMongoDbProvider, pack.NewPackRepository)
