// Code generated by MockGen. DO NOT EDIT.
// Source: C:\go-projects\gympack\pkg\domain\usecase\pack\create\create_pack_usecase_interface.go
//
// Generated by this command:
//
//	mockgen -source=C:\go-projects\gympack\pkg\domain\usecase\pack\create\create_pack_usecase_interface.go -destination=C:\go-projects\gympack\test\mocks\create_pack_usecase_interface_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "gympack/pkg/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreatePackUseCaseInterface is a mock of CreatePackUseCaseInterface interface.
type MockCreatePackUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePackUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockCreatePackUseCaseInterfaceMockRecorder is the mock recorder for MockCreatePackUseCaseInterface.
type MockCreatePackUseCaseInterfaceMockRecorder struct {
	mock *MockCreatePackUseCaseInterface
}

// NewMockCreatePackUseCaseInterface creates a new mock instance.
func NewMockCreatePackUseCaseInterface(ctrl *gomock.Controller) *MockCreatePackUseCaseInterface {
	mock := &MockCreatePackUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockCreatePackUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePackUseCaseInterface) EXPECT() *MockCreatePackUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreatePackUseCaseInterface) Execute(ctx context.Context, pModel model.PackModel) (*model.PackModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, pModel)
	ret0, _ := ret[0].(*model.PackModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreatePackUseCaseInterfaceMockRecorder) Execute(ctx, pModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreatePackUseCaseInterface)(nil).Execute), ctx, pModel)
}
